CREATE DATABASE PROJETO;
USE PROJETO;
CREATE TABLE PESSOA(
	ID	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
	EMAIL VARCHAR(320),
    TELEFONE VARCHAR(20),
    SENHA	VARCHAR(255),
    TEXTO_CONFIRMA	VARCHAR(6),
    TIPO_USER	INT
)ENGINE = InnoDB;
CREATE TABLE COTACAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_SOLICITACAO DATETIME,
    IND_STATUS 	INT,
    DATA_ALTERACAO DATETIME,
    COTACAO decimal(7,2),
    ID_PESSOA INT
    
)ENGINE = InnoDB;
ALTER TABLE `COTACAO` ADD CONSTRAINT `fk_pessoa_cotacao` FOREIGN KEY ( `ID_PESSOA` ) REFERENCES `PESSOA` ( `ID` ) ;

